# .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'
    - 'spec/**/*'  # Skip spec files for now to avoid RSpec cop issues

# Prefer single quotes for consistency
Style/StringLiterals:
  EnforcedStyle: single_quotes

# Allow longer lines in some cases
Layout/LineLength:
  Max: 120

# Allow longer methods for CLI parsing and table formatting
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'lib/lall/cli.rb'
    - 'lib/lall/table_formatter.rb'

# Allow longer classes for main CLI and table formatter
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'lib/lall/cli.rb'
    - 'lib/lall/table_formatter.rb'

# Allow more complex CLI parsing and table formatting
Metrics/CyclomaticComplexity:
  Max: 25
  Exclude:
    - 'lib/lall/table_formatter.rb'
    - 'lib/lotus/environment.rb'

Metrics/PerceivedComplexity:
  Max: 25
  Exclude:
    - 'lib/lall/table_formatter.rb'
    - 'lib/lotus/environment.rb'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'lib/lall/table_formatter.rb'
    - 'lib/lall/key_searcher.rb'

# Allow more parameters for table formatting and search methods
Metrics/ParameterLists:
  Max: 10
  Exclude:
    - 'lib/lall/key_searcher.rb'

# Ignore empty placeholder files
Lint/EmptyFile:
  Exclude:
    - 'lib/lall/environment.rb'
    - 'lib/lall/group.rb'
    - 'lib/lall/lotus_runner.rb'

# Gemspec development dependencies are acceptable in gemspec files
Gemspec/DevelopmentDependencies:
  Enabled: false

# Disable some style cops that don't fit our needs
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
