# config/settings.yml
groups:
  staging:
    - staging
    - staging-s2
    - staging-s3
  prod-us:
    - prod
    - prod-s2
    - prod-s3
    - prod-s4
    - prod-s5
    - prod-s6
    - prod-s7
    - prod-s8
    - prod-s9
  prod-all:
    - prod
    - prod-s2
    - prod-s3
    - prod-s4
    - prod-s5
    - prod-s6
    - prod-s7
    - prod-s8
    - prod-s9
    - prod-s201
    - prod-s101

# Cache configuration
cache:
  # Cache TTL in seconds (default: 1 hour)
  ttl: 3600
  # Local cache directory (default: ~/.lall/cache)
  # Can be overridden by LALL_CACHE_DIR environment variable
  directory: ~/.lall/cache
  # Cache key prefix (default: lall-cache)
  # Can be overridden by LALL_CACHE_PREFIX environment variable
  prefix: lall-cache
  # Enable/disable caching (default: true)
  # Can be overridden by LALL_CACHE_ENABLED environment variable
  enabled: true
  # Secret encryption key file (default: ~/.lall/secret.key)
  # If file doesn't exist, a new key will be generated
  # Can be overridden by LALL_SECRET_KEY_FILE environment variable
  secret_key_file: ~/.lall/secret.key

# Output formatting
output:
  # Placeholder text shown for secret values when not exposing secrets (default: '{SECRET}')
  secret_placeholder: '{SECRET}'
  
  # Color settings for table output
  colors:
    # Environment-only value (no group value present)
    from_env: white
    # Group value with no environment override
    from_group: blue
    # Environment overrides group value (different from group)
    env_changes_group: yellow
    # Environment matches group value (same as group)
    env_mirrors_group: green
